### ISSUE TITLE
Notifications on expiring soon

### ISSUE THREAD

**Issue by KarlReyes28** [KarlReyes28/Expired#10]
As a user, I want to be able to **receive notifications** when my product is **expiring soon**.

**Comment by donghua-shen** [comment]
- The notification will be dispatched two days before expiration by default.
- The notification will be dispatched by “customized expiring soon settings”(if any) before expiration.
- There will be no in-app notification when the user is using the App.
- When the user taps a notification, it will bring the user to the products page.

**Comment by donghua-shen** [comment]
> The notification will be dispatched by “customized expiring soon settings”(if any) before expiration.

**Note**: This feature will be done after implementing "customized expiring soon settings" in future sprints.
